[package]
name = "Helloworldsampleenclave"
version = "1.0.0"
authors = ["Baidu"]

[lib]
name = "helloworldsampleenclave"
crate-type = ["staticlib"]

[features]
default = ["std"]
std = []

[dependencies]
parity-scale-codec = { path = "../../..", features = ["std", "bit-vec", "generic-array", "derive"] }
serde = { git = "https://github.com/mesalock-linux/serde-sgx.git", features = ["derive"] }
parity-scale-codec-derive = { path = "../../../derive", version = "^1.0.2" }
bitvec = { git = "https://github.com/mesalock-linux/bitvec-sgx.git" }
typenum = "1.10"
byte-slice-cast = { git = "https://github.com/mesalock-linux/byte-slice-cast-sgx.git" }
arrayvec = { version = "0.5.1", default-features = false, features = ["array-sizes-33-128", "array-sizes-129-255"] }
generic-array = { version = "0.13.2" }

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { rev = "v1.1.0", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tstd = { rev = "v1.1.0", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tunittest = {rev = "v1.1.0", git = "https://github.com/apache/teaclave-sgx-sdk.git" }

[workspace]
